# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  hugo.version: '0.62.0'
  hugo.theme.path: 'themes/mind-blown'

steps:
- script: pwd
  displayName: 'Current directory'

- script: ls -al
  displayName: 'Files in directory'

- script: wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb
  displayName: 'Download HUGO'

- script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
  displayName: 'Install HUGO'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: $(hugo.theme.path)

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'compile'
    workingDirectory: $(hugo.theme.path)
    enableCodeCoverage: false

- script: 'HUGO_ENV=production hugo -v'
  displaName: 'Build HUGO blog'

- task: Bash@3
  inputs:
    filePath: './scripts/deploy-gh-pages.sh build'