# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  hugo.version: '0.62.0'
  hugo.theme.path: 'themes/mind-blown'
  vmImage: 'ubuntu-latest'
  tag: '$(Build.BuildNumber)'

stages:
- stage: Download and Install Hugo
  displayName: Download hugo and install it
  jobs:
  - job: Download and Install Hugo
    pool:
      vmImage: $(vmImage)
    steps:
    - script: wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb
      displayName: 'Download HUGO'
    - script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
      displayName: 'Install HUGO'
    - publish: manifests
      artifact: manifests

- stage: Compile static assets
  dependsOn:
    - Download and Install Hugo
  displayName: Download hugo and install it
  jobs:
  - job: Download and install
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: $(hugo.theme.path)
    - task: Gulp@1
      inputs:
        gulpFile: 'gulpfile.js'
        targets: 'compile'
        gulpjs: $(hugo.theme.path)
        enableCodeCoverage: false

- stage: 
  dependsOn:
    - Download and Install Hugo
  displayName: Download hugo and install it
  jobs:
  - job: Compile static assets
    pool:
      vmImage: $(vmImage)
    steps:
    - script: 'HUGO_ENV=production hugo -v'
      displayName: 'Build HUGO blog'