# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  gh_user: misky1986
  gh_repo: misky-blog  
  gh_email: mskydt86@gmail.com
  gh_auth_header: $(echo -n "${gh_user}:$(github_pat)" | base64);
  hugoVersion: '0.62.2'
  hugoThemePath: 'themes/mind-blown'
  vmImage: 'ubuntu-latest'
  tag: '$(Build.BuildNumber)'

stages:
- stage: CompileStaticAssets
  displayName: Install NPM packages and compile assets with Gulp
  jobs:
  - job: CompileAssetsWithGulp
    pool:
      vmImage: $(vmImage)
    steps:    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: $(hugoThemePath)
    - task: Gulp@1
      inputs:
        gulpFile: $(hugoThemePath)/gulpfile.js
        targets: 'compile'
        enableCodeCoverage: false
    - publish: ./
      artifact: blogWithAssets    

- stage: BuildBlog
  dependsOn:
    - CompileStaticAssets
  displayName: Build Hugo blog
  jobs:
  - job: BuildHugoBlog
    pool:
      vmImage: $(vmImage)
    steps:
    - checkout: none
    - download: current
      artifact: blogWithAssets
    - script: wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugoVersion)/hugo_$(hugoVersion)_Linux-64bit.deb
      displayName: 'Download HUGO'
    - script: 'sudo dpkg -i hugo_$(hugoVersion)_Linux-64bit.deb'
      displayName: 'Install HUGO'
    - script: |
        cd $(Pipeline.Workspace)/blogWithAssets
        hugo
      displayName: 'Build HUGO blog'
    - publish: $(Pipeline.Workspace)/blogWithAssets/public
      artifact: misky-blog-build
    - publish: $(Pipeline.Workspace)/blogWithAssets/scripts
      artifact: misky-blog-deploy

- stage: DeployToGitHubPages
  dependsOn:
    - BuildBlog
  displayName: Deploy blog to Github pages
  jobs:
  - job: DeployBlogToGithubPages
    pool:
      vmImage: $(vmImage)
    steps:
    - checkout: none
    - download: current
      artifact: misky-blog-build
    - download: current
      artifact: misky-blog-deploy
      path: $(Pipeline.Workspace)/misky-blog-build
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'azure-pipeline-deploy'
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'azure-pipeline-deploy'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkd8hXPXdHDHVWfUGevB2DOG1Wusp/3pyIZRkt/UjWYAwFua2ENcu6cYXbxo3i/t1iguoZZvMpJNGTbsFjLw6ikOTTr8THcqi6EfXF+drGTnmWh/sJEoArgUVv7SWHpBI6fFZcnI8dg0oEOJySc5ZhH1KDOLUB05JZ+KQImWxauQhMMB6GLPy9/DJpQMMsE3YFg4lEZnSdwonfcdhat+quaEteHz6yzM9g/R3ih4QqKnSvMnMbxbtcV1fRLaW9JrLJH/xvCyJKqTVpUwzBZTFeS0sFT3xF0RJilcmivQfk3qm/xllOWamkKOQZ4Qxv7xLR5vIno/toJfJBIrbiEqKpaOKOEx30b3nZs8lKW7M3zfBZxIhKuVAOHahy4qsp3YcfoyHp8TStY8z+pcSGHhkv2MI6zUzDyPhSutkJ7x7qSXnHrnkukMgQCuA7xVQ2JqU7avvMM8mriMWWOkre8PjCuanypS0ZV5wfgpRcYUtvfNiAXR165yVocLzwC6WAMwRCBBlupEOMFqBlEFh8rBPFWdjYpBlPV8NJ6BYKgUznA5DOf3KhcXo3jU0ju93cKCK5JDA1KDUDWoMydYKGEOXEO1gkNxT1lSw7Gi6JgN4iUxMTyfTKKAbxBF1y91C8BAuQS4cD5WQZmYvGzVj0kjVWxoBRlxUsv8FGXn/M2ZeiJw== mskydt86@gmail.com'
        sshKeySecureFile: 'azure-pipeline-deploy'
    - script: |        
        cd $(Pipeline.Workspace)/misky-blog-build        
        deploy-gh-pages.sh