# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  hugoVersion: '0.62.0'
  hugoThemePath: 'themes/mind-blown'
  vmImage: 'ubuntu-latest'
  tag: '$(Build.BuildNumber)'

stages:
- stage: DownloadAndInstallHugo
  displayName: Download hugo and install it
  jobs:
  - job: DownloadAndInstallHugo
    pool:
      vmImage: $(vmImage)
    steps:
    - script: wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugoVersion)/hugo_$(hugoVersion)_Linux-64bit.deb
      displayName: 'Download HUGO'
    - script: 'sudo dpkg -i hugo_$(hugoVersion)_Linux-64bit.deb'
      displayName: 'Install HUGO'

- stage: CompileStaticAssets
  dependsOn:
    - DownloadAndInstallHugo
  displayName: Download NPM and install assets withs Gulp
  jobs:
  - job: CompileAssetsWithGulp
    pool:
      vmImage: $(vmImage)
    steps:    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: $(hugoThemePath)
    - task: Gulp@1
      inputs:
        gulpFile: $(hugoThemePath)/gulpfile.js
        targets: 'compile'
        enableCodeCoverage: false

- stage: Build
  dependsOn:
    - CompileStaticAssets
  displayName: Build Hugo blog
  jobs:
  - job: BuildHugoBlog
    pool:
      vmImage: $(vmImage)
    steps:
    - script: 'hugo'
      displayName: 'Build HUGO blog'

    - publish: public
      artifact: misky-blog-build