theme = "mind-blown"

baseURL = "http://example.org/"
relativeURLs = true

languageCode = "en-us"

[params]
  title = "Misky's home"
  programming = "My life as developer"
  Categories = "CATEGORIES"
  Archives = "ARCHIVES"
  Search = "SEARCH"
  Name = "Michael Skydt"
  github = "https://github.com/misky1986"
  linkedin = "https://www.linkedin.com/in/michael-skydt-41042526/"
  twitter = "https://twitter.com/mskydt"
  stackoverflow = "https://stackoverflow.com/users/1046512/mskydt86"

# Code highlight
pygmentsCodeFences = true
pygmentsUseClasses = true

disqusShortname = "mbd-1"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 100

  # [[menu.main]]
  #   identifier = "tags"
  #   name = "Tags"
  #   url = "/tags/"
  #   weight = 110

  # [[menu.main]]
  #   identifier = "posts"
  #   name = "Posts"
  #   url = "/posts/"
  #   weight = 120
