theme = "mind-blown"

baseURL = "http://example.org/"
relativeURLs = true

languageCode = "en-us"

# Disqus shortname
disqusShortname = "mbd-1"
paginate = 3

[params]
  title = "Misky's home"
  programming = "My life as developer"
  Categories = "CATEGORIES"
  Archives = "ARCHIVES"
  Search = "SEARCH"
  Name = "Michael Skydt"
  github = "https://github.com/misky1986"
  linkedin = "https://www.linkedin.com/in/michael-skydt-41042526/"
  twitter = "https://twitter.com/mskydt"
  stackoverflow = "https://stackoverflow.com/users/1046512/mskydt86"

# Code highlight
pygmentsUseClasses = false
pygmentsCodefences = true

# Setting output formats
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Site Menus
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 100
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 0
