version: 2.1

workflows:
  version: 2.1
  main:
    jobs:
      - compileAssets
      - build:
          requires:
            - compileAssets
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

commands:
  gulp-compile-assets:    
    steps:
      - run:
          command: |            
            sudo npm install -g gulp
            cd themes/mind-blown
            sudo sudo npm install
            sudo gulp compile
            ls -al static/

jobs:
  compileAssets:
    working_directory: ~/github.com/hugo/misky-blog
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout      
      - gulp-compile-assets
      - persist_to_workspace:
          root: themes/mind-blown/
          path: static

  build:
    docker:
      - image: cibuilds/hugo:0.54
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
                    
  deploy:
    docker:
      - image: cibuilds/hugo:0.54
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d1:78:d8:62:40:3c:d8:7a:ad:2f:e6:b3:75:4b:f1:95"
      - run:
          name: Deployment started
          command: bash ./scripts/deploy-gh-pages.sh build
