workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.54    
    steps:
      - checkout      
      - run:
          name: "Run Hugo"          
          command: HUGO_ENV=production hugo -v -s /root/project/
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer /root/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
  deploy:
    docker:
      - image: cibuilds/hugo:0.54
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9e:9d:51:9d:4b:9e:91:5e:05:88:82:84:b7:99:91:6b"
      - run:
          name: Deployment started
          command: bash ./scripts/deploy-gh-pages.sh build